name: Tests

on:
  push:
     branches: [ dev, master ]
     paths:
      - '**.cs'
      - '**.csproj'
      - '**.proto'
      - 'build-proto.fsx'
      - '.github/workflows/Tests.yml'
  pull_request:
    branches: [ dev ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.proto'
      - 'build-proto.fsx'
      - '.github/workflows/Tests.yml'


jobs:
  build-and-test:

    name: tests
    runs-on: windows-10-dev 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build
      run: |
        dotnet fsi build.fsx
    - name: Test
      run: |
        cd Tests
        dotnet test Tests.csproj
