name: Tests

on:
  push:
     branches: [ dev, master ]
     paths:
      - '**.cs'
      - '**.csproj'
      - '**.proto'
      - 'build-proto.fsx'
      - '.github/workflows/Tests.yml'
  pull_request:
    branches: [ dev ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.proto'
      - 'build-proto.fsx'
      - '.github/workflows/Tests.yml'


jobs:
  build-and-test:

    name: tests
    runs-on: fedora-40-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
            '8.0.x'
            '6.0.x'
            '4.8.1'

    - name: Build
      run: |
        dotnet fsi build.fsx
    - name: Test
      run: |
        cd Tests
        dotnet test Tests.csproj
